### ISSUE TITLE
IndexOutOfBoundsException (NEWEST VERSION)

### ISSUE THREAD

**Issue by MAZUU** [Blackvein/Quests#378]
An error has occurred with Quests. Please report on Github. Include the info below
[08:37:05 INFO]: index = -1
[08:37:05 INFO]: locationsReached = []
[08:37:05 WARN]: java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
[08:37:05 WARN]:        at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
[08:37:05 WARN]:        at java.util.LinkedList.get(LinkedList.java:476)
[08:37:05 WARN]:        at me.blackvein.quests.Quester.reachLocation(Quester.java:1213)
[08:37:05 WARN]:        at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:1007)
[08:37:05 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[08:37:05 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:37:05 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[08:37:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[08:37:05 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[08:37:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[08:37:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[08:37:05 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[08:37:05 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[08:37:05 WARN]:        at java.lang.Thread.run(Thread.java:745)
[08:37:05 INFO]: An error has occurred with Quests. Please report on Github. Include the info below
[08:37:05 INFO]: index = -1
[08:37:05 INFO]: locationsReached = []
[08:37:05 WARN]: java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
[08:37:05 WARN]:        at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
[08:37:05 WARN]:        at java.util.LinkedList.get(LinkedList.java:476)
[08:37:05 WARN]:        at me.blackvein.quests.Quester.reachLocation(Quester.java:1213)
[08:37:05 WARN]:        at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:1007)
[08:37:05 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[08:37:05 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:37:05 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[08:37:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[08:37:05 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[08:37:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[08:37:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[08:37:05 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[08:37:05 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[08:37:05 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[08:37:05 WARN]:        at java.lang.Thread.run(Thread.java:745)
[08:37:06 INFO]: Keno29 issued server command: /quest

**Comment by FlyingPikachu** [comment]
Update to #352 

@MAZUU Thank you for updating the issue. This particular bug is difficult. Do you have any quests where the player must reach a certain location? If so, please post your quests.yml

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
