### ISSUE TITLE
IndexOutOfBoundsException when trying to add second mob to event

### ISSUE THREAD

**Issue by nodar86** [Blackvein/Quests#386]
When trying to save a second mob added to an event > spawnmob it throws this error at the console, and gives me back the "Add mob" prompt in-game:

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_91]
        at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_91]
        at me.blackvein.quests.EventFactory$QuestMobPrompt.acceptInput(EventFactory.java:2140) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1044) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1197) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by FlyingPikachu** [comment]
Sorry no-one was able to assist you with this issue. The latest dev build improves the QuestMob class and may resolve this problem. If not, please open a new ticket. Thanks!
