### ISSUE TITLE
One more error during PlayerQuitEvent.

### ISSUE THREAD

**Issue by madtomic** [Blackvein/Quests#40]
[14:18:59 ERROR]: Could not pass event PlayerQuitEvent to Quests v2.0.0 org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at net.minecraft.server.v1_7_R3.PlayerList.disconnect(PlayerList.java:307) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:705) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:130) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at java.util.LinkedList.checkElementIndex(Unknown Source) [?:1.8.0_25] at java.util.LinkedList.get(Unknown Source) [?:1.8.0_25] at me.blackvein.quests.Quester.getObjectives(Quester.java:628) [?:?] at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:420) [?:? ] at me.blackvein.quests.Quester.updateJournal(Quester.java:299) [?:?] at me.blackvein.quests.QuestData$10.add(QuestData.java:314) [?:?] at me.blackvein.quests.QuestData$10.add(QuestData.java:309) [?:?] at me.blackvein.quests.Quester.loadData(Quester.java:2729) [?:?] at me.blackvein.quests.Quests.getQuester(Quests.java:2471) [?:?] at me.blackvein.quests.PlayerListener.onPlayerQuit(PlayerListener.java:831) [?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [?:1.8.0_25] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [?:1.8.0_25] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [?:1.8.0_25] at java.lang.reflect.Method.invoke(Unknown Source) [?:1.8.0_25] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) [craftbukkit179r03.jar:git-Bukkit-1.7.9-R0.2-1-ga6e0bfd-b3095jnks] ... 11 more

**Comment by Pr0totype2** [comment]
I confirm, I get this error;

```
25.12 13:06:57 [Server] INFO Pr0totype2 left the game.
25.12 13:06:57 [Server] INFO ... 12 more
25.12 13:06:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
25.12 13:06:57 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
25.12 13:06:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
25.12 13:06:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
25.12 13:06:57 [Server] INFO at me.blackvein.quests.PlayerListener.onPlayerQuit(PlayerListener.java:939) ~[?:?]
25.12 13:06:57 [Server] INFO at me.blackvein.quests.Quester.saveData(Quester.java:2038) ~[?:?]
25.12 13:06:57 [Server] INFO at me.blackvein.quests.Quester.getBaseData(Quester.java:2090) ~[?:?]
25.12 13:06:57 [Server] INFO Caused by: java.lang.NullPointerException
25.12 13:06:57 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
25.12 13:06:57 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:312) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-db6de12-18fbb24]
25.12 13:06:57 [Server] INFO org.bukkit.event.EventException
25.12 13:06:57 [Server] ERROR Could not pass event PlayerQuitEvent to Quests v2.5.3-b93
25.12 13:06:57 [Disconnect] User Pr0totype2 has disconnected, reason: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
```

Version: 

![image](https://cloud.githubusercontent.com/assets/8803519/12002743/ccde0690-ab08-11e5-947d-ad066507711d.png)
