### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by Sprungente** [Blackvein/Quests#405]
When I bring the item to the npc the item will remove from inventory but the queststage will not ended and plugin mean he has no item gotten. 

Console says:

20.08 22:11:53 [Server] ERROR Could not pass event NPCRightClickEvent to Quests v2.7.2-b114
20.08 22:11:53 [Server] INFO org.bukkit.event.EventException
20.08 22:11:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:385) [citizens-2.0.16-SNAPSHOT.jar:?]
20.08 22:11:53 [Server] INFO at sun.reflect.GeneratedMethodAccessor1892.invoke(Unknown Source) ~[?:?]
20.08 22:11:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
20.08 22:11:53 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
20.08 22:11:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
20.08 22:11:53 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
20.08 22:11:53 [Server] INFO Caused by: java.lang.NullPointerException
20.08 22:11:53 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot187.jar:git-Spigot-21fe707-e1ebe52]
20.08 22:11:53 [Server] INFO at me.blackvein.quests.Quester.deliverItem(Quester.java:1404) ~[?:?]
20.08 22:11:53 [Server] INFO at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:74) ~[?:?]
20.08 22:11:54 [Multicraft] Skipped 5 lines due to rate limit (30/s)

From the quests.yml:
  custom8:
    name: Strandparty
    npc-giver-id: 181
    ask-message: Heute steigt hier eine riesen Strandparty, aber mir fehlen noch einpaar Dinge. Hilfst du mir?
    finish-message: Danke! Lass uns feiern! :D
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-FLOWER_POT_ITEM:amount-12
          npc-delivery-ids:
          - 181
          delivery-messages:
          - Bringe dem Barceeper die 12 Trinkbecher
          start-message: Kannst du mir bitte 12 Trinkbecher bringen?
        '2':
          items-to-deliver:
          - name-MELON:amount-32
          npc-delivery-ids:
          - 181
          delivery-messages:
          - Bring dem Barceeper 32 Melonen
          start-message: "Ich habe die Melonen vergessen! Bitte bring mir Melonen\
            \ f\xfcr die Cocktails!"
    rewards:
      money: 300
      quest-points: 1

I'm using a recommended build for Citizens and the last recommended 1.8 spigotversion. Quests works with 2.7.2

**Comment by dadee971** [comment]
Same error with Quests 2.7.1 and quests 2.7.2, with CraftBukkit version git-Spigot-2486fb7-60c1719 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT) You are running the latest version.
No errors with 2.7.0. Tested with Citizens version  2.0.20 #1411 #1412 #1413 #1414.
