### ISSUE TITLE
NPCRightClickEvent

### ISSUE THREAD

**Issue by Platinteufel** [Blackvein/Quests#417]
If I right-click a NPC to deliver the item I'll get this NPE:
```
[00:49:20 ERROR]: Could not pass event NPCRightClickEvent to Quests v2.7.3-b116
org.bukkit.event.EventException
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-846]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-846]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-846]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-846]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-846]
at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:412) [citizens-2.0.20-SNAPSHOT.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor520.execute(Unknown Source) [?:?]
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) [patched_1.10.2.jar:git-Paper-846]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [patched_1.10.2.jar:git-Paper-846]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.10.2.jar:git-Paper-846]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-846]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-846]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1571) [patched_1.10.2.jar:git-Paper-846]
at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:48) [patched_1.10.2.jar:git-Paper-846]
at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:5) [patched_1.10.2.jar:git-Paper-846]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-846]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-846]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-846]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-846]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-846]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-846]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[patched_1.10.2.jar:git-Paper-846]
at me.blackvein.quests.Quester.deliverItem(Quester.java:1411) ~[?:?]
at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:74) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor533.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-846]
... 23 more
```

**Comment by SliderKP** [comment]
i get the same problem, no fix?

**Comment by Eternirya** [comment]
error at "Material m = null" at line 1395 in source code, hope you fix this @FlyingPikachu

**Comment by jomjonejame** [comment]
I same this problem

**Comment by BloodSKreaper** [comment]
#430
