### ISSUE TITLE
Deliver item to NPC

### ISSUE THREAD

**Issue by titidelaff** [Blackvein/Quests#445]
Hi,

I created a quest where one must give 10 stone to an NPC and when I click on the NPC nothing happens, the quest ends but no reward.

`[18:01:01 ERROR]: Could not pass event NPCRightClickEvent to Quests v2.7.3-b116
org.bukkit.event.EventException
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:412) [citizens-2.0.20-SNAPSHOT.jar:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1533) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
>       at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
>       at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       at me.blackvein.quests.Quester.deliverItem(Quester.java:1411) ~[?:?]
>       at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:74) ~[?:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
>       ... 24 more`

**Comment by zenandreas** [comment]
I'm havint the same issue, how is this not answered for 22 days?

`[00:19:48] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v2.7.3-b116
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[rpg.jar:git-Spigot-f950f8e-41ade2f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[rpg.jar:git-Spigot-f950f8e-41ade2f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414) [citizens-2.0.21-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1518) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [rpg.jar:git-Spigot-f950f8e-41ade2f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[rpg.jar:git-Spigot-f950f8e-41ade2f]
	at me.blackvein.quests.Quester.deliverItem(Quester.java:1411) ~[?:?]
	at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:74) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[rpg.jar:git-Spigot-f950f8e-41ade2f]
	... 23 more`

**Comment by Augustin37** [comment]
Same issue! Delivering function is part of at least 75% of quests! This must be fixed :/

**Comment by johnsoncui02** [comment]
same issue as of 1/15/2017. just so everyone knows how long it's been

**Comment by FlyingPikachu** [comment]
If this is still an issue on newer builds, please open a new ticket. Thanks!
