### ISSUE TITLE
Trying to save a Quest, receiving error.

### ISSUE THREAD

**Issue by CyBlue2995** [Blackvein/Quests#449]
Hello! I am trying to save a quest, and I keep receiving the same error.
I am running on spigot 1.10.2-R0.1-SNAPSHOT
Quests is version 2.7.3-b116
Citizens is version 2.0.21-SNAPSHOT (build 1451)
MY quests.yml config is empty at the moment (I was also receiving the error when there were the 3 starter quests).

Error I keep receiving while trying to save a new quest.

[13:37:35 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
        at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1031) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1044) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1207) [spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:742) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by xBloodlust-ZarkyMC-Head-Dev** [comment]
I get the same problem
