### ISSUE TITLE
Missing some feature (MC1.9+ D: ) / Quests2.7.4

### ISSUE THREAD

**Issue by NoblessHamster** [Blackvein/Quests#451]
Tested Minecraft Server :  1.11 Spigot
Plugin Version : Quests 2.7.4
(Dev build. Build #118: http://ci.ac3-servers.eu/job/Quests/lastBuild/)

If I try to register an item in version 1.9 or later with the Component for editing delivery Quest stage, Error message appears on the console.
(Elytra(1.9), MagmaBlock(1.10), Totem(1.11), ...etc)

Please look this error logs!
If this error is a structural error, I hope it can be solved as soon as possible... :D
Thanks!  良い一日を \(*>.<)/

[22:14:55] [Server thread/WARN]: java.lang.NullPointerException
[22:14:55] [Server thread/WARN]: 	at me.blackvein.quests.util.ItemUtil.getName(ItemUtil.java:220)
[22:14:55] [Server thread/WARN]: 	at me.blackvein.quests.prompts.CreateStagePrompt.getPromptText(CreateStagePrompt.java:172)
[22:14:55] [Server thread/WARN]: 	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291)
[22:14:55] [Server thread/WARN]: 	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230)
[22:14:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58)
[22:14:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066)
[22:14:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1184)
[22:14:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24)
[22:14:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749)
[22:14:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:14:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[22:14:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[22:14:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by FlyingPikachu** [comment]
What version of Vault are you using?

**Comment by NoblessHamster** [comment]
https://dev.bukkit.org/projects/vault/files/894359

DevBukkit/Vault 1.5.6 (1.8+)

**Comment by FlyingPikachu** [comment]
@NoblessHamster In the link you provided, it says in the changelog "This version of Vault will only work on Bukkit/Spigot 1.8+". Please update to compatible version of Vault.

This will be made more clear in the future via commit ef9297910c08ebeeb10c57a80d2533b6f9ad936c

**Comment by NoblessHamster** [comment]
Okay. I'll try that. Thank you
