### ISSUE TITLE
Urgent Issue! Cant edit quest.

### ISSUE THREAD

**Issue by DrakeEldridge** [Blackvein/Quests#457]
Hi. We are making a really big quest, it's pretty huge (Due to all the dialogue, has a lot of stages since dialogue doesn't seem possible to do without stage after stage of start and complete messages. Want to use denizens for dialogue sequences but can't figure out how to add denizen script to quests) Anyway, there is this weird bug where the Quests cannot be edited. We have one quest that has 75 stages, and if we try adding any more, it becomes uneditable. So we split it into 2 quests, and that the second quest which only have 8 stages so far, keeps breaking too. If we add a 'reach location' stage or a 'kill npc' stage to the second quest, even though it only have 8 stages, it can no longer be edited. We make the quest, save it (It saves fine) and players can even play it. But it cannot be opened in the editor. Can you help fix this or find a way to make adding long dialogue easier or denizen scripts to quests for dialogue. This problem really makes  creating large events hard to do.

**Comment by DrakeEldridge** [comment]
[13:59:53] [Server thread/ERROR]: Error handling conversation prompt
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(Unknown Source) ~[?:1.8.0_111]
	at java.util.LinkedList.get(Unknown Source) ~[?:1.8.0_111]
	at me.blackvein.quests.Stage$3.equals(Stage.java:104) ~[?:?]
	at me.blackvein.quests.Stage.equals(Stage.java:236) ~[?:?]
	at java.util.LinkedList.indexOf(Unknown Source) ~[?:1.8.0_111]
	at me.blackvein.quests.QuestFactory.loadQuest(QuestFactory.java:1914) ~[?:?]
	at me.blackvein.quests.QuestFactory$SelectEditPrompt.acceptInput(QuestFactory.java:467) ~[?:?]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1044) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1207) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:742) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by DrakeEldridge** [comment]
when i enter the quest name to edit it that shows up in console
