### ISSUE TITLE
MythicMobs bug.

### ISSUE THREAD

**Issue by johnsoncui02** [Blackvein/Quests#468]
[01:54:30] [Server thread/ERROR]: Could not pass event MythicMobDeathEvent to Quests v2.7.5-b119
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.elseland.xikage.MythicMobs.Adapters.Bukkit.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:303) [MythicMobs.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:392) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1078) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.EntitySkeletonAbstract.die(EntitySkeletonAbstract.java:120) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.EntitySkeletonWither.die(SourceFile:66) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:932) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1023) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1141) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1568) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoSuchMethodError: net.elseland.xikage.MythicMobs.API.Bukkit.Events.MythicMobDeathEvent.getLivingEntity()Lorg/bukkit/entity/LivingEntity;
	at net.elseland.xikage.MythicMobsKillObjective.MythicMobKillObjective.onMythicMobDeath(MythicMobKillObjective.java:43) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]

**Comment by johnsoncui02** [comment]
![image](https://cloud.githubusercontent.com/assets/23487437/22420562/cfb08606-e697-11e6-962e-6c2b12cc6163.png)

**Comment by FlyingPikachu** [comment]
We do not control the MythicMobs module for Quests, so I'm afraid whomever you spoke to was wrong. You should contact Xikage, the author of the module, on Spigot - https://www.spigotmc.org/resources/authors/xikage.19284/
