### ISSUE TITLE
Particle effect error :/

### ISSUE THREAD

**Issue by Max633** [Blackvein/Quests#490]
Hi,

[00:04:08 INFO]: [Quests] happyVillager is not a valid effect name!
[00:04:08 WARN]: java.lang.IllegalArgumentException: No enum constant me.blackvein.particles.Eff_1_11_R1.happyVillager
[00:04:08 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[00:04:08 WARN]:        at me.blackvein.particles.Eff_1_11_R1.valueOf(Eff_1_11_R1.java:11)
[00:04:08 WARN]:        at me.blackvein.quests.NpcEffectThread.showEffect_1_11_R1(NpcEffectThread.java:202)
[00:04:08 WARN]:        at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:87)
[00:04:08 WARN]:        at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:47)
[00:04:08 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[00:04:08 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[00:04:08 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[00:04:08 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[00:04:08 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[00:04:08 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[00:04:08 WARN]:        at java.lang.Thread.run(Thread.java:745)

The plugin does not include all the effects of the game? :/

Thanks

**Comment by FlyingPikachu** [comment]
@Max633 While I would think that should work, try "Happy_Villager" with the underscore.
