### ISSUE TITLE
Can't load Quests - invalid plugin.yml

### ISSUE THREAD

**Issue by Wasserfall159** [Blackvein/Quests#500]
Hello, 
today I downloaded the newest version of Quests, and tried to load it on my server. When I turned on my server, I got this error mesage in console:
`[23:10:00] [Server thread/ERROR]: Could not load 'plugins\Quests-2.7.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
	... 5 more
[23:10:00] [Server thread/INFO]: Set PluginClassLoader as parallel capable
`
I run Spigot version 1.11.2. I start it with this arguments:
`@echo off
java -Xms10G -Xmx10G -jar spigot.jar`
I tried to install older versions of Quests, I also tried to install any other versions of Vault, but nothing helped me. Could somebody please help me in solving my problem? Thanks

**Comment by Daxxas** [comment]
I have the same problem !

**Comment by guilhermefiragi** [comment]
The same error occurred with me, however I went to see and to .jar is missing the plugin.yml so is running the version of craftbukkit but it is for 1.7 and does not receive the items nor receive any items

**Comment by DigitalPenquin** [comment]
5 bucks to the contributors of the plugin if they actually respond... fml

**Comment by Loivado** [comment]
Hey guys,
did you manually change something in the yml? If so make sure to check with a parser if the yml still can be read.

**Comment by Wasserfall159** [comment]
I tried to open the *.jar file using Winrar, I saw some files in there, but when I tried to make some changes or open something, I only got an error mesage „Unexpected end of the archive“. The plugin.yml file isn't anywhere in the jar. 
Maybe the jar file is wrongly compilated. I have no idea what to do with it.

**Comment by DigitalPenquin** [comment]
I've completely stripped my server and ran pure quests and it's dependencies. I've noticed the file size is 24Kb when downloaded; however, the download on the site says it's meant to be 632Kb

**Comment by Reversiya** [comment]
I think this issue was fixed in the latest update as well as the download, which downloads directly from spigot now, not jenkins.

**Comment by Wasserfall159** [comment]
Yes, I tested it and now it's working without errors.
