### ISSUE TITLE
restarting when creating a mob spawn event

### ISSUE THREAD

**Issue by Fargus5** [Blackvein/Quests#518]
[18:02:37] [Server thread/ERROR]: Error handling conversation prompt
java.lang.NumberFormatException: For input string: "null"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_111]
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[?:1.8.0_111]
	at java.lang.Float.parseFloat(Float.java:451) ~[?:1.8.0_111]
	at me.blackvein.quests.util.QuestMob.fromString(QuestMob.java:212) ~[?:?]
	at me.blackvein.quests.EventFactory$MobPrompt.getPromptText(EventFactory.java:1969) ~[?:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1058) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1203) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:757) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[18:02:37] [Server thread/INFO]: [Server] Server is restarting. World is being saved.

**Comment by FlyingPikachu** [comment]
@Fargus5 The latest dev build improves the QuestMob class. Please give it a try and create a new issue with the new error, if you get one. Thanks!
