### ISSUE TITLE
 Unhandled exception executing command 'questadmin'

### ISSUE THREAD

**Issue by nzzane** [Blackvein/Quests#52]
Everytime i do /questadmin reload
I get "an internal error has occurred"
CONSOLE OUTPUT: 
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v1.6.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:534)
	at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1406)
	at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1270)
	at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:1202)
	at net.minecraft.network.packet.Packet3Chat.func_73279_a(Packet3Chat.java:68)
	at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:480)
	at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:234)
	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
	at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:331)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:666)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quests.loadQuests(Quests.java:1717)
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:1641)
	at me.blackvein.quests.Quests.onCommand(Quests.java:1052)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	... 15 more
 
I have reset the config file, and I am not too sure what is causing this error

**Comment by gdianaty** [comment]
Have you tried, by chance, installing Denzien?
