### ISSUE TITLE
Quests Plugin 2.7.6 with Citizens Plugin 2.0.7 (1.4.7)

### ISSUE THREAD

**Issue by Karlos96** [Blackvein/Quests#528]
Here the summary from my other issue: We are currently running a 1.4.7 Modpack Server with a 1.7.10 Bukkit API, so we can accept Plugins from the version 1.4.7 and 1.7.10.
Actually this is not working with citizens, so we are running the 1.4.7 Version but it generates exceptions with the Quests Plugin if the quest is with an citizen.
I hope there is a way to solve this problem because i want to use the newer version of quests instead of the very old quests plugin.

Here the Error-Code:

2017-06-15 19:53:15 [WARNING] [Quests] Task #119 for Quests v2.7.6-b${env.BUILD_NUMBER} generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
	at me.blackvein.quests.NpcEffectThread.showEffect_R4(NpcEffectThread.java:940)
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:69)
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:47)
	at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:347)
	at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:757)
	at ho.r(DedicatedServer.java:309)
	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:715)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602)
	at fy.run(ThreadMinecraftServer.java:16)
2017-06-15 19:53:16 [WARNING] [Quests] Task #119 for Quests v2.7.6-b${env.BUILD_NUMBER} generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
	at me.blackvein.quests.NpcEffectThread.showEffect_R4(NpcEffectThread.java:940)
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:69)
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:47)
	at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:347)
	at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:757)
	at ho.r(DedicatedServer.java:309)
	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:715)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602)
	at fy.run(ThreadMinecraftServer.java:16)
2017-06-15 19:53:17 [WARNING] [Quests] Task #119 for Quests v2.7.6-b${env.BUILD_NUMBER} generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
	at me.blackvein.quests.NpcEffectThread.showEffect_R4(NpcEffectThread.java:940)
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:69)
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:47)
	at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:347)
	at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:757)
	at ho.r(DedicatedServer.java:309)
	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:715)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602)
	at fy.run(ThreadMinecraftServer.java:16)
2017-06-15 19:53:18 [WARNING] [Quests] Task #119 for Quests v2.7.6-b${env.BUILD_NUMBER} generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
	at me.blackvein.quests.NpcEffectThread.showEffect_R4(NpcEffectThread.java:940)
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:69)
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:47)
	at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:347)
	at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:757)
	at ho.r(DedicatedServer.java:309)
	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:715)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602)
	at fy.run(ThreadMinecraftServer.java:16)

**Comment by FlyingPikachu** [comment]
Can I ask which version of Citizens you're running? And could you confirm whether or not show-npc-effects is set to 'true' in config.yml?

**Comment by Karlos96** [comment]
The version of Citizens is in the title Version 2.0.7 for the Minecraft Version 1.4.7 because Citizens does not work with the Bukkit API with the version 1.7.10.
I tested it now but it seems to work if show-npc-effects is set to 'false'.

**Comment by Karlos96** [comment]
Now i created a Quest with an NPC but it generates this exception:


10:22:58 [SEVERE] Exception in thread "Connection #2 read thread"
10:22:58 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getStoredLocation()Lorg/bukkit/Location;
10:22:58 [SEVERE]       at me.blackvein.quests.Quests.getNPCLocation(Quests.java:5146)
10:22:58 [SEVERE]       at me.blackvein.quests.Quest.updateCompass(Quest.java:187)
10:22:58 [SEVERE]       at me.blackvein.quests.Quester.takeQuest(Quester.java:398)
10:22:58 [SEVERE]       at me.blackvein.quests.Quests$QuestPrompt.acceptInput(Quests.java:497)
10:22:58 [SEVERE]       at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228)
10:22:58 [SEVERE]       at org.bukkit.craftbukkit.v1_4_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:52)
10:22:58 [SEVERE]       at org.bukkit.craftbukkit.v1_4_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:894)
10:22:58 [SEVERE]       at iv.chat(NetServerHandler.java:1258)
10:22:58 [SEVERE]       at iv.a(NetServerHandler.java:1188)
10:22:58 [SEVERE]       at cu.a(Packet3Chat.java:59)
10:22:58 [SEVERE]       at cg.i(TcpConnection.java:348)
10:22:58 [SEVERE]       at cg.c(TcpConnection.java:553)
10:22:58 [SEVERE]       at ch.run(TcpReaderThread.java:23)

**Comment by FlyingPikachu** [comment]
Thank you. Unfortunately, I have bad news.

This commit is the culprit - https://github.com/CitizensDev/CitizensAPI/commit/225ac8e275de0e77b571d029828f83c9a633ac0f

Quests is trying to find the `getEntity()` function from Citizens, which was called `getBukkitEntity()` up until Citizens 2.0.10-SNAPSHOT. **Sadly there is no easy fix for this beyond updating to at least 2.0.10. The same goes for your new error.** I understand this is not ideal for your server, but seeing as Quests does not support forks/modpacks and the oldest Bukkit supported is 1.7.9, I'm afraid I cannot further assist you (not that I'd be able to anyway).

I will make a note of the minimum version requirement on the Spigot main page.
