### ISSUE TITLE
Could not pass BlockBreakEvent to Quests v2.8.7-b134

### ISSUE THREAD

**Issue by mitgobla** [Blackvein/Quests#543]
v2.8.7-b134
```
10.07 20:02:35 [Server] ERROR Could not pass event BlockBreakEvent to Quests v2.8.7-b134
10.07 20:02:35 [Server] INFO org.bukkit.event.EventException
10.07 20:02:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:851) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
10.07 20:02:35 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
10.07 20:02:35 [Server] INFO Caused by: java.lang.NullPointerException
10.07 20:02:35 [Server] INFO at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:346) ~[?:?]
10.07 20:02:35 [Server] INFO at me.blackvein.quests.Quester.updateJournal(Quester.java:257) ~[?:?]
10.07 20:02:35 [Server] INFO at me.blackvein.quests.QuestData$2.set(QuestData.java:81) ~[?:?]
10.07 20:02:35 [Server] INFO at me.blackvein.quests.QuestData$2.set(QuestData.java:73) ~[?:?]
10.07 20:02:35 [Server] INFO at me.blackvein.quests.Quester.breakBlock(Quester.java:738) ~[?:?]
10.07 20:02:35 [Server] INFO at me.blackvein.quests.PlayerListener.onBlockBreak(PlayerListener.java:346) ~[?:?]
10.07 20:02:35 [Server] INFO at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source) ~[?:?]
10.07 20:02:35 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
10.07 20:02:35 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
10.07 20:02:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:35 [Server] INFO ... 17 more
10.07 20:02:36 [Server] ERROR Could not pass event BlockBreakEvent to Quests v2.8.7-b134
10.07 20:02:36 [Server] INFO org.bukkit.event.EventException
10.07 20:02:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:851) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
10.07 20:02:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
10.07 20:02:36 [Server] INFO Caused by: java.lang.NullPointerException
10.07 20:02:36 [Server] INFO at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:346) ~[?:?]
10.07 20:02:36 [Server] INFO at me.blackvein.quests.Quester.updateJournal(Quester.java:257) ~[?:?]
10.07 20:02:36 [Server] INFO at me.blackvein.quests.QuestData$2.set(QuestData.java:81) ~[?:?]
10.07 20:02:36 [Server] INFO at me.blackvein.quests.QuestData$2.set(QuestData.java:73) ~[?:?]
10.07 20:02:36 [Server] INFO at me.blackvein.quests.Quester.breakBlock(Quester.java:738) ~[?:?]
10.07 20:02:36 [Server] INFO at me.blackvein.quests.PlayerListener.onBlockBreak(PlayerListener.java:346) ~[?:?]
10.07 20:02:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source) ~[?:?]
10.07 20:02:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
10.07 20:02:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
10.07 20:02:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
10.07 20:02:36 [Server] INFO ... 17 more
```

**Comment by mitgobla** [comment]
Once this error occurs, the entire plugin does not respond to commands.

**Comment by Sprungente** [comment]
This Github-Page is no longer supported

use the new one:

https://github.com/FlyingPikachu/Quests
